name: Enable GCS Versioning

on:
  workflow_dispatch: # Pipeline dapat dijalankan secara manual

jobs:
  enable-versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > gcp-key.json

    - name: Build Docker Image
      run: docker build -t enable-versioning .

    - name: Run Docker Container
      run: docker run \
        -e GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json \
        enable-versioning
